language: java

dist: trusty

jobs:
  include:
    - stage: Build using various JDK versions
      jdk: oraclejdk8
    - jdk: oraclejdk9
    - jdk: openjdk8
    - stage: Test Coverage
      jdk: oraclejdk8
      after_success: mvn clean test jacoco:report coveralls:report
    - stage: Deploy Artifacts
      if: tag IS present
      jdk: oraclejdk8
      before_install:
        - openssl aes-256-cbc -K $encrypted_6678f8a25f19_key -iv $encrypted_6678f8a25f19_iv -in .travis/singingbushgpgkey.asc.enc -out .travis/singingbushgpgkey.asc -d
        - gpg2 --fast-import .travis/singingbushgpgkey.asc
      script: mvn deploy -B --settings=.travis/settings.xml -DskipTests=true
      on:
        tags: true
